"""initial schema: runs, cycle entries, symptoms

Revision ID: 8509008ad75b
Revises:
Create Date: 2026-05-09 21:02:29.316915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (referenced by autogenerated AutoString columns)


# revision identifiers, used by Alembic.
revision: str = '8509008ad75b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycleentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('flow_intensity', sa.Enum('none', 'spotting', 'light', 'medium', 'heavy', name='flowintensity'), nullable=False),
    sa.Column('energy_level', sa.Enum('low', 'medium', 'high', name='energylevel'), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycleentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycleentry_entry_date'), ['entry_date'], unique=True)

    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('pace_min_per_mile', sa.Float(), nullable=False),
    sa.Column('elevation_gain_feet', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('perceived_exertion', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'strava', name='runsource'), nullable=False),
    sa.Column('strava_activity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_strava_activity_id'), ['strava_activity_id'], unique=True)

    op.create_table('symptom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_name'), ['name'], unique=True)

    op.create_table('cycleentrysymptomlink',
    sa.Column('cycle_entry_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_entry_id'], ['cycleentry.id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptom.id'], ),
    sa.PrimaryKeyConstraint('cycle_entry_id', 'symptom_id')
    )
    # ### end Alembic commands ###

    # Seed the fixed symptom list. We define a lightweight table stub here
    # (rather than importing the real Symptom model) so this migration stays
    # pinned to the schema as it exists at THIS revision, not whatever the
    # model looks like in the future.
    symptom_table = sa.table(
        'symptom',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
    )
    op.bulk_insert(
        symptom_table,
        [
            {'name': 'Cramps'},
            {'name': 'Fatigue'},
            {'name': 'Bloating'},
            {'name': 'Back pain'},
            {'name': 'Mood changes'},
            {'name': 'Cravings'},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cycleentrysymptomlink')
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_name'))

    op.drop_table('symptom')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_strava_activity_id'))
        batch_op.drop_index(batch_op.f('ix_run_started_at'))
        batch_op.drop_index(batch_op.f('ix_run_source'))

    op.drop_table('run')
    with op.batch_alter_table('cycleentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycleentry_entry_date'))

    op.drop_table('cycleentry')
    # ### end Alembic commands ###
